# Generated by Django 3.0.2 on 2020-03-01 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_createdTime', models.DateField(db_index=True)),
                ('asset_lastAccessTime', models.DateField(db_index=True)),
                ('asset_symbol', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('asset_symbol_label', models.CharField(max_length=32)),
                ('asset_name', models.CharField(max_length=128)),
                ('asset_currency', models.CharField(max_length=8)),
                ('asset_isException', models.BooleanField(default=False)),
                ('asset_lastTradeTime', models.CharField(db_index=True, max_length=32, null=True)),
                ('asset_price', models.FloatField(null=True)),
                ('asset_volatility', models.FloatField(null=True, verbose_name='Volatility percentage over last 10 days.')),
                ('asset_volume_avg', models.IntegerField(null=True, verbose_name='Volume average over last 10 days.')),
            ],
        ),
        migrations.CreateModel(
            name='D_raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_datetime', models.CharField(db_index=True, max_length=64, unique=True)),
                ('d_datetime', models.CharField(db_index=True, max_length=32)),
                ('d_open', models.FloatField()),
                ('d_high', models.FloatField()),
                ('d_low', models.FloatField()),
                ('d_close', models.FloatField()),
                ('d_volume', models.BigIntegerField()),
                ('asset_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Asset', verbose_name='Asset Symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_datetime', models.CharField(db_index=True, max_length=32)),
                ('log_level', models.CharField(max_length=8)),
                ('log_module', models.CharField(max_length=64)),
                ('log_message', models.TextField(max_length=2048)),
                ('log_created_by', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='StockExchange',
            fields=[
                ('se_short', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Stock Exchange Short')),
                ('se_name', models.CharField(db_index=True, max_length=128, verbose_name='Stock Exchange Name')),
                ('se_startTime', models.TimeField(verbose_name='Usual time the market starts')),
                ('se_endTime', models.TimeField(verbose_name='Usual time the market ends')),
                ('se_timezone', models.CharField(max_length=32, verbose_name='Timezone (TZ database name)')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalCondition',
            fields=[
                ('tc_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('tc_name', models.CharField(max_length=64)),
                ('tc_type', models.CharField(max_length=12)),
                ('tc_description', models.TextField(max_length=2048)),
                ('tc_rating', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_datetime', models.CharField(db_index=True, max_length=64, unique=True)),
                ('su_datetime', models.CharField(db_index=True, max_length=32)),
                ('su_max_price', models.FloatField(null=True)),
                ('su_target', models.FloatField(null=True)),
                ('su_stop_loss', models.FloatField(null=True)),
                ('su_gain_percent', models.FloatField(null=True)),
                ('su_risk_gain', models.FloatField(null=True)),
                ('technical_condition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.TechnicalCondition', verbose_name='Technical Condition details')),
            ],
        ),
        migrations.CreateModel(
            name='D_var',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_datetime', models.CharField(db_index=True, max_length=64, unique=True)),
                ('d_var_closepv72', models.FloatField(null=True, verbose_name='Percent difference between values')),
                ('d_var_closepv305', models.FloatField(null=True, verbose_name='Percent difference between values')),
                ('d_var_closepc72', models.FloatField(null=True, verbose_name='Percent difference between values')),
                ('d_var_closepc305', models.FloatField(null=True, verbose_name='Percent difference between values')),
                ('d_var_lowpv72', models.FloatField(null=True, verbose_name='Percent difference between values')),
                ('d_var_lowpv305', models.FloatField(null=True, verbose_name='Percent difference between values')),
                ('d_var_highpc72', models.FloatField(null=True, verbose_name='Percent difference between values')),
                ('d_var_highpc305', models.FloatField(null=True, verbose_name='Percent difference between values')),
                ('d_var_emaclose1734', models.FloatField(null=True, verbose_name='Percent difference between values')),
                ('d_var_emaclose3472', models.FloatField(null=True, verbose_name='Percent difference between values')),
                ('d_var_emaclose72144', models.FloatField(null=True, verbose_name='Percent difference between values')),
                ('d_var_emaclose144305', models.FloatField(null=True, verbose_name='Percent difference between values')),
                ('d_var_emaclose305610', models.FloatField(null=True, verbose_name='Percent difference between values')),
                ('d_var_emaclose6101292', models.FloatField(null=True, verbose_name='Percent difference between values')),
                ('d_var_emaclose12922584', models.FloatField(null=True, verbose_name='Percent difference between values')),
                ('d_raw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.D_raw', verbose_name='Asset and Datetime')),
            ],
        ),
        migrations.CreateModel(
            name='D_roc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_datetime', models.CharField(db_index=True, max_length=64, unique=True)),
                ('d_roc_close2', models.FloatField(null=True)),
                ('d_roc_close3', models.FloatField(null=True)),
                ('d_roc_high2', models.FloatField(null=True)),
                ('d_roc_low2', models.FloatField(null=True)),
                ('d_roc_emaclose17', models.FloatField(null=True)),
                ('d_roc_emaclose34', models.FloatField(null=True)),
                ('d_roc_emaclose72', models.FloatField(null=True)),
                ('d_roc_emaclose144', models.FloatField(null=True)),
                ('d_roc_emaclose305', models.FloatField(null=True)),
                ('d_roc_emaclose610', models.FloatField(null=True)),
                ('d_roc_emaclose1292', models.FloatField(null=True)),
                ('d_roc_emaclose2584', models.FloatField(null=True)),
                ('d_raw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.D_raw', verbose_name='Asset and Datetime')),
            ],
        ),
        migrations.CreateModel(
            name='D_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_datetime', models.CharField(db_index=True, max_length=64, unique=True)),
                ('d_tc_despvpc', models.CharField(max_length=32, null=True)),
                ('d_tc_desema', models.CharField(max_length=32, null=True)),
                ('d_tc_range', models.CharField(max_length=32, null=True)),
                ('d_tc_trend', models.CharField(max_length=32, null=True)),
                ('d_raw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.D_raw')),
            ],
        ),
        migrations.CreateModel(
            name='D_pvpc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_datetime', models.CharField(db_index=True, max_length=64, unique=True)),
                ('d_pv72', models.FloatField(null=True)),
                ('d_pv144', models.FloatField(null=True)),
                ('d_pv305', models.FloatField(null=True)),
                ('d_pv610', models.FloatField(null=True)),
                ('d_pv1292', models.FloatField(null=True)),
                ('d_pc72', models.FloatField(null=True)),
                ('d_pc144', models.FloatField(null=True)),
                ('d_pc305', models.FloatField(null=True)),
                ('d_pc610', models.FloatField(null=True)),
                ('d_pc1292', models.FloatField(null=True)),
                ('d_pd72', models.FloatField(null=True)),
                ('d_pd144', models.FloatField(null=True)),
                ('d_pd305', models.FloatField(null=True)),
                ('d_pd610', models.FloatField(null=True)),
                ('d_pd1292', models.FloatField(null=True)),
                ('d_raw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.D_raw')),
            ],
        ),
        migrations.CreateModel(
            name='D_ema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_datetime', models.CharField(db_index=True, max_length=64, unique=True)),
                ('d_ema_close17', models.FloatField(null=True)),
                ('d_ema_close34', models.FloatField(null=True)),
                ('d_ema_close72', models.FloatField(null=True)),
                ('d_ema_close144', models.FloatField(null=True)),
                ('d_ema_close305', models.FloatField(null=True)),
                ('d_ema_close610', models.FloatField(null=True)),
                ('d_ema_close1292', models.FloatField(null=True)),
                ('d_ema_close2584', models.FloatField(null=True)),
                ('d_raw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.D_raw')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='stockExchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.StockExchange', verbose_name='Stock Exchange Short'),
        ),
    ]
