# Generated by Django 3.0.2 on 2020-03-01 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_symbol_label',
            new_name='asset_label',
        ),
        migrations.AlterField(
            model_name='asset',
            name='stockExchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='market.StockExchange'),
        ),
    ]
