# Generated by Django 3.0.8 on 2020-07-23 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logging',
            old_name='log_module',
            new_name='context',
        ),
        migrations.RenameField(
            model_name='logging',
            old_name='log_created_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='logging',
            old_name='log_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='logging',
            old_name='log_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='logging',
            old_name='log_datetime',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_considered',
            field=models.BooleanField(default=False, verbose_name='Is considered in the entire App/frontend?'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_considered_for_analysis',
            field=models.BooleanField(default=False, verbose_name='Is considered for Technical Analysis?'),
        ),
        migrations.CreateModel(
            name='AssetProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=8, verbose_name='Alpha-2 Code')),
                ('sector_id', models.CharField(max_length=64, null=True)),
                ('sector_name', models.CharField(max_length=64, null=True)),
                ('website', models.CharField(max_length=64, null=True)),
                ('business_summary', models.TextField()),
                ('asset_symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.Asset')),
            ],
        ),
    ]
