# Generated by Django 3.0.2 on 2020-03-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200301_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_lastAccessTime',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_modifiedTime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_createdTime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
