# Generated by Django 3.0.8 on 2020-07-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200723_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockexchange',
            name='website',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='assetprofile',
            name='website',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
