# Generated by Django 3.0.2 on 2020-03-02 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200301_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicalcondition',
            old_name='tc_rating',
            new_name='tc_score',
        ),
    ]
