# Generated by Django 3.0.8 on 2020-07-23 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200723_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=8, verbose_name='Alpha-2 Code')),
                ('sector_id', models.CharField(max_length=64, null=True)),
                ('sector_name', models.CharField(max_length=64, null=True)),
                ('website', models.CharField(max_length=128, null=True)),
                ('business_summary', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Realtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_trade_time', models.CharField(db_index=True, max_length=32)),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('price', models.FloatField()),
                ('volume', models.BigIntegerField(null=True)),
                ('pct_change', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_lastTradeTime',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_pct_change',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_price',
        ),
        migrations.DeleteModel(
            name='AssetProfile',
        ),
        migrations.AddField(
            model_name='realtime',
            name='asset_symbol',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtime', to='market.Asset'),
        ),
        migrations.AddField(
            model_name='profile',
            name='asset_symbol',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='market.Asset'),
        ),
    ]
