# Generated by Django 3.0.8 on 2020-07-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20200723_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_label',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_name',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='is_considered',
        ),
        migrations.AddField(
            model_name='profile',
            name='asset_label',
            field=models.CharField(default='Temp', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='asset_name',
            field=models.CharField(default='Temp', max_length=128),
            preserve_default=False,
        ),
    ]
