# Generated by Django 3.0.8 on 2020-07-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20200723_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockexchange',
            old_name='se_createdTime',
            new_name='created_time',
        ),
        migrations.RemoveField(
            model_name='stockexchange',
            name='provider_realtime',
        ),
        migrations.RemoveField(
            model_name='stockexchange',
            name='provider_timeseries',
        ),
        migrations.AddField(
            model_name='stockexchange',
            name='modified_time',
            field=models.DateField(auto_now=True),
        ),
    ]
