# Generated by Django 3.0.2 on 2020-05-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_stockexchange_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockexchange',
            name='country_code',
            field=models.CharField(default='BR', max_length=8, verbose_name='Alpha-2 Code'),
            preserve_default=False,
        ),
    ]
