# Generated by Django 3.0.8 on 2020-07-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20200723_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='modified_time',
            field=models.DateField(auto_now=True),
        ),
    ]
