# Generated by Django 3.0.8 on 2020-07-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_profile_modified_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_volatility',
        ),
    ]
