# Generated by Django 3.0.2 on 2020-05-23 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20200524_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_analysis',
            old_name='d_tc_btlema17',
            new_name='d_tc_btlema',
        ),
        migrations.RemoveField(
            model_name='d_analysis',
            name='d_tc_btlema34',
        ),
    ]
