# Generated by Django 3.0.2 on 2020-05-23 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20200524_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_var',
            old_name='d_var_emaclose144305',
            new_name='d_var_emaclose144610',
        ),
        migrations.RenameField(
            model_name='d_var',
            old_name='d_var_emaclose1734',
            new_name='d_var_emaclose34144',
        ),
        migrations.RemoveField(
            model_name='d_analysis',
            name='d_tc_range',
        ),
        migrations.RemoveField(
            model_name='d_ema',
            name='d_ema_close17',
        ),
        migrations.RemoveField(
            model_name='d_ema',
            name='d_ema_close305',
        ),
        migrations.RemoveField(
            model_name='d_ema',
            name='d_ema_close72',
        ),
        migrations.RemoveField(
            model_name='d_pvpc',
            name='d_pc144',
        ),
        migrations.RemoveField(
            model_name='d_pvpc',
            name='d_pd1292',
        ),
        migrations.RemoveField(
            model_name='d_pvpc',
            name='d_pd144',
        ),
        migrations.RemoveField(
            model_name='d_pvpc',
            name='d_pd305',
        ),
        migrations.RemoveField(
            model_name='d_pvpc',
            name='d_pd610',
        ),
        migrations.RemoveField(
            model_name='d_pvpc',
            name='d_pd72',
        ),
        migrations.RemoveField(
            model_name='d_pvpc',
            name='d_pv144',
        ),
        migrations.RemoveField(
            model_name='d_roc',
            name='d_roc_emaclose17',
        ),
        migrations.RemoveField(
            model_name='d_roc',
            name='d_roc_emaclose305',
        ),
        migrations.RemoveField(
            model_name='d_roc',
            name='d_roc_emaclose72',
        ),
        migrations.RemoveField(
            model_name='d_var',
            name='d_var_emaclose305610',
        ),
        migrations.RemoveField(
            model_name='d_var',
            name='d_var_emaclose3472',
        ),
        migrations.RemoveField(
            model_name='d_var',
            name='d_var_emaclose72144',
        ),
    ]
