# Generated by Django 3.0.2 on 2020-05-24 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20200524_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_pvpc',
            name='d_pc610',
        ),
        migrations.RemoveField(
            model_name='d_pvpc',
            name='d_pv610',
        ),
        migrations.RemoveField(
            model_name='d_var',
            name='d_var_closepc305',
        ),
        migrations.RemoveField(
            model_name='d_var',
            name='d_var_closepc72',
        ),
        migrations.RemoveField(
            model_name='d_var',
            name='d_var_closepv305',
        ),
        migrations.RemoveField(
            model_name='d_var',
            name='d_var_closepv72',
        ),
        migrations.RemoveField(
            model_name='d_var',
            name='d_var_highpc305',
        ),
        migrations.RemoveField(
            model_name='d_var',
            name='d_var_highpc72',
        ),
        migrations.RemoveField(
            model_name='d_var',
            name='d_var_lowpv305',
        ),
        migrations.RemoveField(
            model_name='d_var',
            name='d_var_lowpv72',
        ),
    ]
