# Generated by Django 3.0.8 on 2020-08-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20200728_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_setup',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='d_raw',
            name='asset_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='market.Asset', verbose_name='Asset Symbol'),
        ),
    ]
