# Generated by Django 3.0.8 on 2020-10-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20200804_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_ema',
            name='d_ema_close200',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_ema',
            name='d_ema_close50',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_ema',
            name='d_ema_close8',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_ema',
            name='d_ema_close9',
            field=models.FloatField(null=True),
        ),
    ]
