# Generated by Django 3.0.8 on 2020-10-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20201006_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_roc',
            name='d_roc_close2',
        ),
        migrations.RemoveField(
            model_name='d_roc',
            name='d_roc_close3',
        ),
        migrations.RemoveField(
            model_name='d_roc',
            name='d_roc_high2',
        ),
        migrations.RemoveField(
            model_name='d_roc',
            name='d_roc_low2',
        ),
        migrations.RemoveField(
            model_name='d_technicalcondition',
            name='emaroc_btl',
        ),
        migrations.AddField(
            model_name='d_roc',
            name='d_roc_emaclose200',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_roc',
            name='d_roc_emaclose50',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_roc',
            name='d_roc_emaclose8',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_roc',
            name='d_roc_emaclose9',
            field=models.FloatField(null=True),
        ),
    ]
