# Generated by Django 3.0.2 on 2020-05-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_d_analysis_d_tc_pivot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_analysis',
            old_name='d_tc_decpvpc',
            new_name='d_tc_pvpc',
        ),
    ]
