# Generated by Django 3.0.2 on 2020-05-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20200524_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicalcondition',
            old_name='tc_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='technicalcondition',
            old_name='tc_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='technicalcondition',
            old_name='tc_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='technicalcondition',
            old_name='tc_score',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='technicalcondition',
            old_name='tc_type',
            new_name='type',
        ),
    ]
