# Generated by Django 3.0.8 on 2020-10-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20201006_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_sma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_datetime', models.CharField(db_index=True, max_length=64, unique=True)),
                ('d_sma_close10', models.FloatField(null=True)),
                ('d_sma_close20', models.FloatField(null=True)),
                ('d_sma_close21', models.FloatField(null=True)),
                ('d_sma_close50', models.FloatField(null=True)),
                ('d_sma_close55', models.FloatField(null=True)),
                ('d_sma_close100', models.FloatField(null=True)),
                ('d_sma_close200', models.FloatField(null=True)),
                ('d_raw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.D_raw')),
            ],
        ),
    ]
