# Generated by Django 3.0.8 on 2020-10-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_d_sma'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_sma',
            name='d_sma_close30',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_sma',
            name='d_sma_close7',
            field=models.FloatField(null=True),
        ),
    ]
