# Generated by Django 3.0.2 on 2020-05-26 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20200525_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_analysis',
            old_name='tc_pvpc',
            new_name='tc_decpvpc',
        ),
        migrations.AddField(
            model_name='d_analysis',
            name='tc_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='market.TechnicalCondition'),
        ),
    ]
