# Generated by Django 3.0.8 on 2020-10-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20201006_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_roc',
            name='d_roc_smaclose10',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_roc',
            name='d_roc_smaclose100',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_roc',
            name='d_roc_smaclose20',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_roc',
            name='d_roc_smaclose200',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_roc',
            name='d_roc_smaclose21',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_roc',
            name='d_roc_smaclose30',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_roc',
            name='d_roc_smaclose50',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_roc',
            name='d_roc_smaclose55',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_roc',
            name='d_roc_smaclose7',
            field=models.FloatField(null=True),
        ),
    ]
