# Generated by Django 3.1.3 on 2020-11-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_auto_20201007_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_setup',
            name='is_public',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
