# Generated by Django 3.0.2 on 2020-05-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_auto_20200527_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_analysis',
            name='gain_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_analysis',
            name='target',
            field=models.FloatField(null=True),
        ),
    ]
