# Generated by Django 3.1.7 on 2021-03-09 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_auto_20201130_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_raw',
            old_name='asset_symbol',
            new_name='asset',
        ),
    ]
