# Generated by Django 3.0.2 on 2020-05-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_auto_20200527_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_analysis',
            name='risk_reward',
            field=models.FloatField(null=True),
        ),
    ]
