# Generated by Django 3.1.7 on 2021-03-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_auto_20210310_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_var',
            name='d_var_ema_close_8_17',
            field=models.FloatField(null=True, verbose_name='Percent variation between values'),
        ),
    ]
