# Generated by Django 3.0.2 on 2020-05-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_d_analysis_risk_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_analysis',
            name='loss_percent',
            field=models.FloatField(null=True),
        ),
    ]
