# Generated by Django 3.1.7 on 2021-03-10 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_d_var_d_var_ema_close_8_17'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_tc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_datetime', models.CharField(db_index=True, max_length=64, unique=True)),
                ('pivot', models.IntegerField(null=True)),
                ('ema_btl_high', models.IntegerField(null=True)),
                ('ema_btl_low', models.IntegerField(null=True)),
                ('ema_btl_close', models.IntegerField(null=True)),
                ('ema_range', models.IntegerField(null=True)),
                ('ema_trend', models.IntegerField(null=True)),
                ('ema_test', models.IntegerField(null=True)),
                ('phibo_alignment', models.IntegerField(null=True)),
                ('phibo_test', models.IntegerField(null=True)),
                ('d_raw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.d_raw')),
            ],
        ),
        migrations.DeleteModel(
            name='D_technicalCondition',
        ),
    ]
