# Generated by Django 3.0.2 on 2020-05-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_d_analysis_loss_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='log_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
