# Generated by Django 3.1.7 on 2021-03-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_auto_20210310_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_tc',
            name='sma_test',
            field=models.IntegerField(null=True),
        ),
    ]
