# Generated by Django 3.0.2 on 2020-05-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_auto_20200529_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_analysis',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
