# Generated by Django 3.0.2 on 2020-05-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_d_analysis_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_analysis',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
