# Generated by Django 3.1.7 on 2021-03-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_d_tc_sma_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_tc',
            old_name='ema_range',
            new_name='ema_alignment',
        ),
    ]
