# Generated by Django 3.0.2 on 2020-05-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_auto_20200529_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_ema',
            name='d_ema_close17',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_roc',
            name='d_roc_emaclose17',
            field=models.FloatField(null=True),
        ),
    ]
