# Generated by Django 3.1.7 on 2021-03-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_auto_20210312_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_phiOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('is_public', models.BooleanField(default=None, null=True)),
                ('radar_on', models.CharField(max_length=32)),
                ('started_on', models.CharField(max_length=32, null=True)),
                ('ended_on', models.CharField(max_length=32, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('entry_price', models.FloatField()),
                ('target', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('gain_percent', models.FloatField()),
                ('loss_percent', models.FloatField()),
                ('risk_reward', models.FloatField()),
                ('fibonacci', models.JSONField(default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phi_events', to='market.asset')),
                ('d_raw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.d_raw')),
                ('tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phi_events', to='market.technicalcondition')),
            ],
        ),
        migrations.RenameModel(
            old_name='D_setupSummary',
            new_name='D_phiStats',
        ),
        migrations.DeleteModel(
            name='D_setup',
        ),
        migrations.AddConstraint(
            model_name='d_phioperation',
            constraint=models.UniqueConstraint(fields=('asset', 'tc'), name='unique_asset_tc'),
        ),
    ]
