# Generated by Django 3.1.7 on 2021-03-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_auto_20210313_2017'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='d_phioperation',
            name='unique_asset_tc',
        ),
        migrations.AddConstraint(
            model_name='d_phioperation',
            constraint=models.UniqueConstraint(fields=('asset', 'tc', 'radar_on'), name='unique_asset_tc'),
        ),
    ]
