# Generated by Django 3.0.2 on 2020-06-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_auto_20200603_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_var',
            old_name='d_var_emaclose12922584',
            new_name='d_var_emaclose72305',
        ),
    ]
