# Generated by Django 3.0.2 on 2020-06-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_auto_20200603_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_var',
            old_name='d_var_emaclose72305',
            new_name='d_var_emaclose12922584',
        ),
        migrations.RemoveField(
            model_name='d_ema',
            name='d_ema_close305',
        ),
        migrations.RemoveField(
            model_name='d_ema',
            name='d_ema_close72',
        ),
        migrations.RemoveField(
            model_name='d_roc',
            name='d_roc_emaclose305',
        ),
        migrations.RemoveField(
            model_name='d_roc',
            name='d_roc_emaclose72',
        ),
    ]
