# Generated by Django 3.1.7 on 2021-03-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_auto_20210319_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_phioperation',
            name='entry_price',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='d_phioperation',
            name='gain_percent',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='d_phioperation',
            name='loss_percent',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='d_phioperation',
            name='risk_reward',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='d_phioperation',
            name='stop_loss',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='d_phioperation',
            name='target',
            field=models.JSONField(default=dict),
        ),
    ]
