# Generated by Django 3.0.2 on 2020-06-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_auto_20200603_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_ema',
            name='d_ema_close305',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_ema',
            name='d_ema_close72',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_roc',
            name='d_roc_emaclose305',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_roc',
            name='d_roc_emaclose72',
            field=models.FloatField(null=True),
        ),
    ]
