# Generated by Django 3.0.2 on 2020-06-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0027_auto_20200604_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_var',
            old_name='d_var_emaclose12922584',
            new_name='d_var_emaclose144305',
        ),
        migrations.RenameField(
            model_name='d_var',
            old_name='d_var_emaclose144610',
            new_name='d_var_emaclose1734',
        ),
        migrations.RenameField(
            model_name='d_var',
            old_name='d_var_emaclose34144',
            new_name='d_var_emaclose305610',
        ),
        migrations.RenameField(
            model_name='d_var',
            old_name='d_var_emaclose6101292',
            new_name='d_var_emaclose3472',
        ),
        migrations.AddField(
            model_name='d_var',
            name='d_var_emaclose72144',
            field=models.FloatField(null=True, verbose_name='Percent variation between values'),
        ),
    ]
