# Generated by Django 3.0.2 on 2020-06-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0029_auto_20200605_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_analysis',
            name='ema_range',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
