# Generated by Django 3.1.7 on 2021-03-25 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0030_auto_20210322_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='stockExchange',
            new_name='stock_exchange',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='asset_symbol',
            new_name='asset',
        ),
    ]
