# Generated by Django 3.0.2 on 2020-06-06 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0030_d_analysis_range_ema'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_setupRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_setup', models.CharField(db_index=True, max_length=64, unique=True)),
                ('success_rate', models.FloatField(default=None)),
                ('streak_max', models.IntegerField(default=None)),
                ('asset_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Asset')),
                ('tc_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.TechnicalCondition')),
            ],
        ),
    ]
