# Generated by Django 3.0.2 on 2020-06-08 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0031_d_setuprating'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_datetime', models.CharField(db_index=True, max_length=64, unique=True)),
                ('max_price', models.FloatField(null=True)),
                ('target', models.FloatField(null=True)),
                ('stop_loss', models.FloatField(null=True)),
                ('gain_percent', models.FloatField(null=True)),
                ('loss_percent', models.FloatField(null=True)),
                ('risk_reward', models.FloatField(null=True)),
                ('d_raw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.D_raw')),
                ('tc_setup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.TechnicalCondition')),
            ],
        ),
        migrations.CreateModel(
            name='D_technicalCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_datetime', models.CharField(db_index=True, max_length=64, unique=True)),
                ('pivot', models.IntegerField(null=True)),
                ('ema_btl', models.IntegerField(null=True)),
                ('btl_emaroc', models.IntegerField(null=True)),
                ('phibo_alignment', models.IntegerField(null=True)),
                ('phibo_test', models.IntegerField(null=True)),
                ('ema_range', models.IntegerField(null=True)),
                ('ema_trend', models.IntegerField(null=True)),
                ('d_raw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.D_raw')),
            ],
        ),
        migrations.DeleteModel(
            name='D_analysis',
        ),
    ]
