# Generated by Django 3.1.7 on 2021-03-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0031_auto_20210325_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtime',
            old_name='asset_symbol',
            new_name='asset',
        ),
    ]
