# Generated by Django 3.1.7 on 2021-03-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0032_auto_20210326_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_phioperation',
            name='entry_price',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='d_phioperation',
            name='gain_percent',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='d_phioperation',
            name='loss_percent',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='d_phioperation',
            name='risk_reward',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='d_phioperation',
            name='stop_loss',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='d_phioperation',
            name='target',
            field=models.JSONField(default=list),
        ),
    ]
