# Generated by Django 3.0.2 on 2020-06-08 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0032_auto_20200608_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_technicalCondition2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_datetime', models.CharField(db_index=True, max_length=64, unique=True)),
                ('pivot', models.IntegerField(null=True)),
                ('ema_btl', models.IntegerField(null=True)),
                ('emaroc_btl', models.IntegerField(null=True)),
                ('ema_range', models.IntegerField(null=True)),
                ('ema_trend', models.IntegerField(null=True)),
                ('phibo_alignment', models.IntegerField(null=True)),
                ('phibo_test', models.IntegerField(null=True)),
                ('d_raw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.D_raw')),
            ],
        ),
        migrations.AddField(
            model_name='d_setup',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='D_technicalCondition',
        ),
    ]
