# Generated by Django 3.1.7 on 2021-04-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0033_auto_20210326_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockexchange',
            old_name='se_name',
            new_name='name',
        ),
    ]
