# Generated by Django 3.0.2 on 2020-06-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0033_auto_20200608_1254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='D_technicalCondition2',
            new_name='D_technicalCondition',
        ),
    ]
