# Generated by Django 3.0.2 on 2020-06-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0034_auto_20200608_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_setup',
            name='tc_setup',
        ),
        migrations.AddField(
            model_name='d_setup',
            name='tcId',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
