# Generated by Django 3.1.7 on 2021-04-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0035_auto_20210414_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m60_ema',
            old_name='m60_raw',
            new_name='raw',
        ),
        migrations.RenameField(
            model_name='m60_phioperation',
            old_name='m60_raw',
            new_name='raw',
        ),
        migrations.RenameField(
            model_name='m60_pvpc',
            old_name='m60_raw',
            new_name='raw',
        ),
        migrations.RenameField(
            model_name='m60_raw',
            old_name='m60_datetime',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='m60_roc',
            old_name='m60_raw',
            new_name='raw',
        ),
        migrations.RenameField(
            model_name='m60_sma',
            old_name='m60_raw',
            new_name='raw',
        ),
        migrations.RenameField(
            model_name='m60_tc',
            old_name='m60_raw',
            new_name='raw',
        ),
        migrations.RenameField(
            model_name='m60_var',
            old_name='m60_raw',
            new_name='raw',
        ),
    ]
