# Generated by Django 3.0.2 on 2020-06-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0035_auto_20200608_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_setup',
            old_name='tcId',
            new_name='tc_id',
        ),
    ]
