# Generated by Django 3.0.2 on 2020-06-08 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0036_auto_20200608_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_setup',
            name='tc_id',
        ),
        migrations.AddField(
            model_name='d_setup',
            name='tc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='market.TechnicalCondition'),
            preserve_default=False,
        ),
    ]
