# Generated by Django 3.1.7 on 2021-04-17 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0037_auto_20210417_0630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_ema',
            old_name='d_raw',
            new_name='raw',
        ),
        migrations.RenameField(
            model_name='d_phioperation',
            old_name='d_raw',
            new_name='raw',
        ),
        migrations.RenameField(
            model_name='d_pvpc',
            old_name='d_raw',
            new_name='raw',
        ),
        migrations.RenameField(
            model_name='d_roc',
            old_name='d_raw',
            new_name='raw',
        ),
        migrations.RenameField(
            model_name='d_sma',
            old_name='d_raw',
            new_name='raw',
        ),
        migrations.RenameField(
            model_name='d_tc',
            old_name='d_raw',
            new_name='raw',
        ),
        migrations.RenameField(
            model_name='d_var',
            old_name='d_raw',
            new_name='raw',
        ),
        migrations.AlterField(
            model_name='d_raw',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_raws', to='market.asset', verbose_name='Asset Symbol'),
        ),
    ]
