# Generated by Django 3.0.2 on 2020-06-10 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0038_auto_20200608_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_setupHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_started_on_tc', models.CharField(db_index=True, max_length=64, unique=True)),
                ('started_on', models.CharField(max_length=32)),
                ('ended_on', models.CharField(max_length=32, null=True)),
                ('duration', models.IntegerField()),
                ('target', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('asset_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Asset')),
                ('tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.TechnicalCondition')),
            ],
        ),
        migrations.CreateModel(
            name='D_setupSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_setup', models.CharField(db_index=True, max_length=64, unique=True)),
                ('gain_count', models.IntegerField(default=0)),
                ('loss_count', models.IntegerField(default=0)),
                ('avg_duration_gain', models.IntegerField(default=None)),
                ('avg_duration_loss', models.IntegerField(default=None)),
                ('last_ended_occurrence', models.CharField(db_index=True, max_length=32)),
                ('last_ended_duration', models.IntegerField(default=None)),
                ('last_was_successful', models.BooleanField(default=None)),
                ('asset_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Asset')),
                ('tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.TechnicalCondition')),
            ],
        ),
        migrations.RemoveField(
            model_name='d_setup',
            name='is_public',
        ),
        migrations.DeleteModel(
            name='D_setupRating',
        ),
    ]
