# Generated by Django 3.0.2 on 2020-06-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0039_auto_20200610_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_setupsummary',
            name='asset_symbol',
        ),
        migrations.RemoveField(
            model_name='d_setupsummary',
            name='tc',
        ),
        migrations.AddField(
            model_name='d_setup',
            name='duration',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='d_setup',
            name='ended_on',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='d_setup',
            name='is_success',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='d_setup',
            name='started_on',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='D_setupHistory',
        ),
        migrations.DeleteModel(
            name='D_setupSummary',
        ),
    ]
