# Generated by Django 3.1.7 on 2021-04-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0039_auto_20210421_0940'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='m60_phioperation',
            name='m60_phioperation__asset_tc_date',
        ),
        migrations.AddConstraint(
            model_name='m60_phioperation',
            constraint=models.UniqueConstraint(fields=('asset', 'radar_on'), name='m60_phioperation__asset_datetime'),
        ),
    ]
