# Generated by Django 3.0.2 on 2020-06-11 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0040_auto_20200611_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_setupSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_setup', models.CharField(db_index=True, max_length=64, unique=True)),
                ('has_position_open', models.BooleanField(default=False)),
                ('gain_count', models.IntegerField(default=0)),
                ('loss_count', models.IntegerField(default=0)),
                ('avg_duration_gain', models.IntegerField(null=True)),
                ('avg_duration_loss', models.IntegerField(null=True)),
                ('last_ended_occurrence', models.CharField(db_index=True, max_length=32)),
                ('last_ended_duration', models.IntegerField(null=True)),
                ('last_was_successful', models.BooleanField(null=True)),
                ('asset_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Asset')),
                ('tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.TechnicalCondition')),
            ],
        ),
    ]
