# Generated by Django 3.0.2 on 2020-06-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0041_d_setupsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_setupsummary',
            name='success_rate',
            field=models.FloatField(default=0),
        ),
    ]
