# Generated by Django 3.0.2 on 2020-06-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0042_d_setupsummary_success_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_setupsummary',
            old_name='last_was_successful',
            new_name='last_was_success',
        ),
    ]
