# Generated by Django 3.0.2 on 2020-06-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0043_auto_20200611_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_technicalcondition',
            old_name='ema_btl',
            new_name='low_ema_btl',
        ),
    ]
