# Generated by Django 3.0.2 on 2020-06-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0044_auto_20200611_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_technicalcondition',
            name='high_ema_btl',
            field=models.IntegerField(null=True),
        ),
    ]
