# Generated by Django 3.0.2 on 2020-06-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0045_d_technicalcondition_high_ema_btl'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_technicalcondition',
            name='ema_test',
            field=models.IntegerField(null=True),
        ),
    ]
