# Generated by Django 3.0.2 on 2020-06-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0046_d_technicalcondition_ema_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_setup',
            name='asset_setup',
            field=models.CharField(db_index=True, default=None, max_length=64),
            preserve_default=False,
        ),
    ]
