# Generated by Django 3.0.2 on 2020-06-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0047_d_setup_asset_setup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='D_setup',
        ),
    ]
