# Generated by Django 3.0.2 on 2020-06-13 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0048_delete_d_setup'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_datetime', models.CharField(db_index=True, max_length=64, unique=True)),
                ('asset_setup', models.CharField(db_index=True, max_length=64)),
                ('started_on', models.CharField(max_length=32, null=True)),
                ('ended_on', models.CharField(max_length=32, null=True)),
                ('is_success', models.BooleanField(null=True)),
                ('duration', models.IntegerField(default=True)),
                ('max_price', models.FloatField(null=True)),
                ('target', models.FloatField(null=True)),
                ('stop_loss', models.FloatField(null=True)),
                ('gain_percent', models.FloatField(null=True)),
                ('loss_percent', models.FloatField(null=True)),
                ('risk_reward', models.FloatField(null=True)),
                ('d_raw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.D_raw')),
                ('tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.TechnicalCondition')),
            ],
        ),
    ]
