# Generated by Django 3.0.2 on 2020-06-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0049_d_setup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
