# Generated by Django 3.0.2 on 2020-06-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0050_delete_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_change_percent',
            field=models.FloatField(null=True),
        ),
    ]
