# Generated by Django 3.0.2 on 2020-06-13 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0051_asset_asset_change_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_change_percent',
            new_name='asset_pct_change',
        ),
    ]
