# Generated by Django 3.0.2 on 2020-06-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0052_auto_20200614_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_setup',
            name='fibo_p1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_setup',
            name='fibo_p2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_setup',
            name='fibo_p3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_setup',
            name='fibo_pct_retraction',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_setup',
            name='fibo_projection',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_setup',
            name='fibo_retraction',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='d_setup',
            name='fibo_wave_1',
            field=models.FloatField(null=True),
        ),
    ]
