# Generated by Django 3.0.2 on 2020-06-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0053_auto_20200616_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_setup',
            name='fibo_periods_needed',
            field=models.FloatField(null=True),
        ),
    ]
