# Generated by Django 3.0.2 on 2020-06-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0055_auto_20200617_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_setupsummary',
            name='occurrencies',
            field=models.IntegerField(default=0),
        ),
    ]
