# Generated by Django 3.0.2 on 2020-07-03 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0056_d_setupsummary_occurrencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_currency',
        ),
        migrations.AddField(
            model_name='stockexchange',
            name='se_createdTime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
