# Generated by Django 3.0.2 on 2020-07-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0057_auto_20200703_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_createdTime',
            new_name='asset_created_time',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_isException',
            new_name='asset_is_exception',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_modifiedTime',
            new_name='asset_modified_time',
        ),
        migrations.AddField(
            model_name='asset',
            name='last_access_time',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
