# Generated by Django 3.0.2 on 2020-07-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0058_auto_20200703_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_created_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_modified_time',
            new_name='modified_time',
        ),
    ]
