# Generated by Django 3.0.8 on 2020-07-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0060_auto_20200707_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_is_ignorable',
            new_name='consider_for_analysis',
        ),
    ]
