# Generated by Django 3.0.8 on 2020-07-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0061_auto_20200707_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockexchange',
            name='provider_realtime',
            field=models.CharField(default='AV', max_length=8),
        ),
        migrations.AddField(
            model_name='stockexchange',
            name='provider_timeseries',
            field=models.CharField(default='AV', max_length=8),
        ),
        migrations.AlterField(
            model_name='stockexchange',
            name='se_endTime',
            field=models.TimeField(default='18:00:00', verbose_name='Usual time the market ends'),
        ),
        migrations.AlterField(
            model_name='stockexchange',
            name='se_startTime',
            field=models.TimeField(default='10:00:00', verbose_name='Usual time the market starts'),
        ),
    ]
