# Generated by Django 3.0.8 on 2020-07-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0062_auto_20200713_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='consider_for_analysis',
        ),
        migrations.AddField(
            model_name='asset',
            name='is_considered',
            field=models.BooleanField(default=False, verbose_name='Is it considered in the entire App/frontend?'),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_considered_for_analysis',
            field=models.BooleanField(default=False, verbose_name='Is it considered in Setup classes?'),
        ),
    ]
