# Generated by Django 3.0.8 on 2020-07-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0063_auto_20200714_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_lastTradeTime',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_access_time',
            field=models.DateField(db_index=True, default='2001-01-01'),
        ),
    ]
